const fs = require('fs');
const path = require('path');

// Determine which env to use based on APP_ENV environment variable, default to 'test'
const env = process.env.APP_ENV || 'test';
const envFile = env === 'production' ? '.env.prod' : '.env.test';
const envPath = path.resolve(__dirname, '..', envFile);

console.log(`[Env Loader] Reading environment file: ${envFile}`);

let envContent = '';
try {
  envContent = fs.readFileSync(envPath, 'utf8');
} catch (err) {
  console.warn(`[Env Loader] Warning: Could not read ${envFile}, using empty config.`);
}

const envVars = {};
envContent.split(/\r?\n/).forEach(line => {
  // Ignore comments and empty lines
  const trimmedLine = line.trim();
  if (!trimmedLine || trimmedLine.startsWith('#')) return;

  const match = trimmedLine.match(/^([\w.-]+)\s*=\s*(.*)?\s*$/);
  if (match) {
    const key = match[1];
    let value = match[2] || '';
    // Remove wrapping quotes if any
    if (value.length > 0 && value.charAt(0) === '"' && value.charAt(value.length - 1) === '"') {
      value = value.substring(1, value.length - 1);
    }
    envVars[key] = value;
  }
});

const outputContent = `// Generated by scripts/load-env.js
// Do not edit this file directly. Instead, modify .env.test or .env.prod and run the environment loader.
export const ENV = ${JSON.stringify(envVars, null, 2)} as const;
`;

fs.writeFileSync(path.resolve(__dirname, '..', 'env.ts'), outputContent, 'utf8');
console.log(`[Env Loader] Successfully generated env.ts`);
